version: 0.2

phases:
  build:
    commands:
      - mvn clean install

artifacts:
  files:
    - target/ceevee-ssl-server-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - runapp.sh
    - stopapp.sh
  discard-paths: yes
