version: 0.2

phases:
  build:
    commands:
      - mvn clean install

artifacts:
  files:
    - target/*.jar
    - appspec.yaml
    - runapp.sh
    - stopapp.sh
    - Dockerfile
  discard-paths: yes
